<?php

$s = '';

$s.= '<p>' . $this->markdown->parse($this->tutorial->text) . '</p>'.N;

$this->setSlot('pagetitle', $this->tutorial->title . ' - Projects');
$this->setSlot('meta.description', $this->tutorial->intro);
$keywords = '';
if ($this->tutorial->keywords) {
    $keywords = $this->tutorial->keywords;
}
$this->setSlot('meta.keywords', $keywords);
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));