<?php

$this->setSlot('form', $this->form);

$s = '';

$s.= '<h2>Contact</h2>'.N;

$s.= '<div class="table-heading">Some title</div>'.N;
$s.= '<form action="" method="post">'.N;
$this->setSlot('form.field', 'csrf-token');
$s.= $this->render('form/render_formfield.phtml');
$s.= '<table>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Name *</th>'.N;
$this->setSlot('form.field', 'name');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Emailaddress *</th>'.N;
$this->setSlot('form.field', 'email');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Subject *</th>'.N;
$this->setSlot('form.field', 'subject');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Message *</th>'.N;
$this->setSlot('form.field', 'message');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>&nbsp;</th>'.N;
$this->setSlot('form.field', 'submit');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '</table>'.N;
$s.= '</form>'.N;

$this->setSlot('pagetitle', 'Contact');
$this->setSlot('meta.description', '');
$this->setSlot('meta.keywords', 'pieter,hordijk,contact,email');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));