<?php

$s = '';

$s.= '<p>Contact request sent from the website.</p>'.N;
$s.= '<table>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>From</th>'.N;
$s.= '    <td>' . $this->form->getField('name')->getData() . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Email</th>'.N;
$s.= '    <td>' . $this->form->getField('email')->getData() . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Subject</th>'.N;
$s.= '    <td>' . $this->form->getField('subject')->getData() . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '</table>'.N;

$s.= '<p>' . $this->form->getField('message')->getData() . '</p>' .N;

print($s);