<?php

$s = '';

$s.= '<h2>Authorization required</h2>'.N;
$s.= '<p>You do not have permission to access this resource.</p>'.N;

$this->setSlot('pagetitle', 'Forbidden');
$this->setSlot('meta.description', 'You do not have permission to access this resource.');
$this->setSlot('meta.keywords', '');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));