<?php

$s = '';

$s.= '<h2>Page not found</h2>'.N;
$s.= '<p>The resource you have requested cannot be found. Please verify the URL and try again.</p>'.N;

$this->setSlot('pagetitle', 'Not found');
$this->setSlot('meta.description', 'The resource you have requested cannot be found. Please verify the URL and try again.');
$this->setSlot('meta.keywords', '');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));