<?php

$this->setSlot('form', $this->form);

$s = '';

$s.= '<h2>Add new track</h2>'.N;

$s.= '<div class="table-heading">Some title</div>'.N;
$s.= '<form action="" method="post" enctype="multipart/form-data">'.N;
$this->setSlot('form.field', 'csrf-token');
$s.= $this->render('form/render_formfield.phtml');
$s.= '<table>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Soundcloud id *</th>'.N;
$this->setSlot('form.field', 'id');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>&nbsp;</th>'.N;
$this->setSlot('form.field', 'submit');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '</table>'.N;
$s.= '</form>'.N;

$this->setSlot('pagetitle', 'Add new track - Music');
$this->setSlot('meta.description', '');
$this->setSlot('meta.keywords', '');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));