<?php

$s = '';

$s.= '<h2>Music</h2>'.N;
$s.= '<p>Below you will find some of the tracks I have produced. You can find more of my music on <a href="http://soundcloud.com/sander-van-halem" target="_blank">Soundcloud</a>.</p>'.N;

foreach($this->tracks as $track) {
    $this->setSlot('soundcloud.id', $track->soundcloudId);
    $s.= $this->render('music/player.phtml');
}

$this->setSlot('pagetitle', 'Music');
$this->setSlot('meta.description', 'An overview of tracks I\'ve produced.');
$this->setSlot('meta.keywords', 'Pieter Hordijk, music, sound, tracks, music production, soundcloud, sander van halem, sound engineer, dance');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));