<h1>Demos</h1>
<table class="demos">
    <tr>
        <th class="name">Name</th>
        <th class="description">Description</th>
    </tr>
    <tr class="clickable">
        <td class="name"><a href="https://commentar.pieterhordijk.com/comments/1" target="_blank">Commentar</a></td>
        <td class="description">Commentar is a self hosted open source commenting system which can easily be integrated into any existing system. It is a highly modular system and based on the "don't need it don't inlude it" principle. For an overview of the currently provided modules please see the organization's <a href="https://github.com/Commentar" target="_blank">GitHub profile</a>. Commentar is an <a href="/open-source/15/commentar">open source project</a>.</td>
    </tr>
    <tr class="clickable">
        <td class="name"><a href="https://emailtester.pieterhordijk.com/" target="_blank">EmailTester</a></td>
        <td class="description">Tests regex patterns to match emailaddresses against a list of known valid and invalid emailaddresses. EmailTester is an <a href="/open-source/12/emailtester">open source project</a>.</td>
    </tr>
    <tr class="clickable">
        <td class="name"><a href="https://hexdump.pieterhordijk.com" target="_blank">HexDump</a></td>
        <td class="description">An online hex dump tool. Either paste a string or upload a file to see the hexadecimal representation of it. Useful for debugging. All converted hex dumps are automatically saved for 1 week. HexDump is an <a href="/open-source/4/hexdump">open source project</a>.</td>
    </tr>
    <tr class="clickable">
        <td class="name"><a href="http://uploader.pieterhordijk.com" target="_blank">RichUploader</a></td>
        <td class="description">A private file locker. A nice and convenient way to share your files. It uses a fancy drag-and-drop (multiple) file uploader and keeps track of upload progress. After uploading file download can be set to either public (anyone can download), private (only the owner can download) or password protected. RichUploader is an <a href="/open-source/7/uploader">open source project</a>.</td>
    </tr>
    <tr class="clickable">
        <td class="name"><a href="https://passhash.pieterhordijk.com" target="_blank">PassHash</a></td>
        <td class="description">This is a very simple utility website which hashes a password using PHP's native password hashing function. The use cases will be very narrow, but sometimes when developing a new project I want to quickly be able to generate a password hash to change a password directly in the database and I am too lazy to fire up one of the PHP codepads that is up at that time.</td>
    </tr>
    <tr class="clickable">
        <td class="name"><a href="https://webmonitor.pieterhordijk.com" target="_blank">WebMonitor</a></td>
        <td class="description">Free of charge (for open source projects and friends) monitoring service for webservices. It periodically checks the webservices and displays metrics. WebMonitor allows you to setup multiple monitors for different domains. If you are interested and want to check it out feel free to ask for an <a href="https://webmonitor.pieterhordijk.com/register" target="_blank">invitation</a> and I will send it to you shortly.</td>
    </tr>
</table>
