<h1>PieterHordijk.com</h1>
<p>This site mainly exists as an index for the projects I'm working on and because people have been bugging me about setting up my site again for more than a year.</p>
<p>On this site you will find all the projects I have worked on or am still working on both open source and closed source.</p>
<h2>Can I steal this site?</h2>
<p>I have no idea why you would want to steal my site (I'm a developer and not a designer), but <a href="https://github.com/PeeHaa/pieterhordijk.com">here you go</a>. It is <a href="http://www.dbad-license.org/" target="_blank">DBAD</a> licensed.</p>