<?php
use PieterHordijk\OpenSource\Collection,
    PieterHordijk\OpenSource\ProjectFactory,
    Artax\Client;

$collection = new Collection($dbConnection, new Client(), new ProjectFactory());
$projects   = $collection->get();
?>

<h1>Open source projects</h1>
<table class="opensource">
    <tr>
        <th class="name">Name</th>
        <th class="description">Description</th>
        <th class="languages">Languages</th>
        <th class="watchers">Watchers</th>
        <th class="forks">Forks</th>
        <th class="status">Status</th>
    </tr>
    <?php if (empty($projects)) { ?>
        <tr>
            <td colspan="5" class="empty">No open source projects have been added yet.</td>
        </tr>
    <?php } else { ?>
        <?php foreach ($projects as $project) { ?>
            <tr>
                <td class="name"><?php echo $project->getName(); ?></td>
                <td class="description"><?php echo $project->getShortDescription(); ?></td>
                <td class="languages"><?php echo $project->getLanguage(); ?></td>
                <td class="watchers"><?php echo $project->getWatchers(); ?></td>
                <td class="forks"><?php echo $project->getForks(); ?></td>
                <?php $status = $project->getStatus() ? '<img src="' . $project->getStatus() . '">' : ''; ?>
                <td class="status"><?php echo $status; ?></td>
            </tr>
        <?php } ?>
    <?php } ?>
</table>
