<!DOCTYPE html>
<html>
    <head>
        <title>Pieter Hordijk</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href='//fonts.googleapis.com/css?family=Lato:300italic,700italic,300,700' rel='stylesheet' type='text/css'>
        <link href="/style/style.css" rel="stylesheet" type="text/css" media="screen"></style>
    </head>
    <body>
        <header>
            <div class="content">
                <h1>Pieter Hordijk</h1>
                <nav>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Open source</a></li>
                        <li><a href="#">Projects</a></li>
                        <li><a href="#">Demos</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="#">About</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <main>
            <?php echo $content; ?>
        </main>
        <footer>
            <div class="content">
                <ul>
                    <li><h1>Open source</h1>
                        <ul>
                            <li><a href="#">OpCacheGUI - a nice webinterface for PHP's OpCache</a></li>
                            <li><a href="#">HexDump - an online hex viewer</a></li>
                            <li><a href="#">RichUploader - a private filehoster</a></li>
                            <li><a href="#">PHP OAuth library</a></li>
                            <li><a href="#">Proposal for the new beginners tutorial on php.net</a></li>
                            <li><a href="#">Show all</a></li>
                        </ul>
                    </li>
                    <li><h1>Demos</h1>
                        <ul>
                            <li><a href="https://hexdump.pieterhordijk.com/" target="_blank">HexDump - an online hex viewer</a></li>
                            <li><a href="http://uploader.pieterhordijk.com" target="_blank">RichUploader - a private filehoster</a></li>
                            <li><a href="https://webmonitor.pieterhordijk.com" target="_blank">WebMonitor - Monitors you servers for you</a></li>
                            <li>&nbsp;</li>
                            <li>&nbsp;</li>
                            <li><a href="#">Show all</a></li>
                        </ul>
                    </li>
                    <li class="flair">
                        <ul>
                            <li><iframe src="//githubbadge.appspot.com/badge/PeeHaa?a=0" style="border: 0;height: 142px;width: 200px;overflow: hidden;" frameBorder="0"></iframe></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <ul class="legal">
                <li>Copyright © 2013 Pieter Hordijk</li>
            </ul>
        </footer>
        <script src="/js/main.js"></script>
    </body>
</html>
