<!DOCTYPE html>
<html>
    <head>
        <title>Pieter Hordijk</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href='//fonts.googleapis.com/css?family=Lato:300italic,700italic,300,700' rel='stylesheet' type='text/css'>
        <link href="/style/style.css" rel="stylesheet" type="text/css" media="screen"></style>
    </head>
    <body>
        <header>
            <div class="content">
                <h1>Pieter Hordijk</h1>
                <nav>
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><a href="/open-source">Open source</a></li>
                        <li><a href="/demos">Demos</a></li>
                        <li><a href="/tutorials">Tutorials</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </header>
        <main>
            <?php echo $content; ?>
        </main>
        <footer>
            <div class="content">
                <ul>
                    <li><h1>Open source</h1>
                        <ul>
                            <li><a href="/open-source/10/opcachegui">OpCacheGUI - a nice webinterface for PHP's OpCache</a></li>
                            <li><a href="/open-source/4/hexdump">HexDump - an online hex viewer</a></li>
                            <li><a href="/open-source/7/uploader">RichUploader - a private filehoster</a></li>
                            <li><a href="/open-source/11/phpoauthlib">PHP OAuth library</a></li>
                            <li><a href="/open-source/8/php-tutorial">Proposal for the new beginners tutorial on php.net</a></li>
                            <li><a href="/open-source">Show all</a></li>
                        </ul>
                    </li>
                    <li><h1>Demos</h1>
                        <ul>
                            <li><a href="https://hexdump.pieterhordijk.com/" target="_blank">HexDump - an online hex viewer</a></li>
                            <li><a href="http://uploader.pieterhordijk.com" target="_blank">RichUploader - a private filehoster</a></li>
                            <li><a href="https://webmonitor.pieterhordijk.com" target="_blank">WebMonitor - Monitors your servers for you</a></li>
                            <li>&nbsp;</li>
                            <li>&nbsp;</li>
                            <li><a href="/demos">Show all</a></li>
                        </ul>
                    </li>
                    <li class="flair">
                        <ul>
                            <li><iframe src="//githubbadge.appspot.com/badge/PeeHaa?a=0" style="border: 0;height: 142px;width: 200px;overflow: hidden;" frameBorder="0"></iframe></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <ul class="legal">
                <li>Copyright © 2013 Pieter Hordijk</li>
            </ul>
        </footer>
        <script src="/js/main.js"></script>
        <script type="text/javascript">

          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-31938084-1']);
          _gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();

        </script>
    </body>
</html>
