<h1>Tutorials</h1>
<table class="tutorials">
    <tr>
        <th class="name">Name</th>
        <th class="description">Description</th>
    </tr>
    <tr class="clickable">
        <td class="name"><a href="/tutorials/linux-nginx-php-postgresql">Setting up a secure linux webserver with mail</a></td>
        <td class="description">Installation instructions for a full web stack and server hardening using Linux, Nginx, PHP and PostgreSQL.</td>
    </tr>
</table>
