<?php

$s = '';

$s.= '<aside>'.N;
$s.= '  <div class="info">'.N;
if ($this->project->image || $this->project->download) {
    $s.= '    <div class="image">'.N;
    if ($this->project->image) {
        $s.= '      <img src="/img/projects/' . $this->project->image . '" alt="' . $this->project->title . '" title="' . $this->project->title . '">'.N;
    }
    if ($this->project->download) {
        $s.= '      <a href="' . $this->project->download . '">Download</a>'.N;
    }
    $s.= '    </div>'.N;
}
$s.= '    <ul>'.N;
$s.= '      <li><strong>' . $this->project->title . '</strong></li>'.N;
if (property_exists($this->project->github, 'username')) {
    $githubUrl = 'https://github.com/' . $this->project->github->username . '/' . $this->project->github->repo;
    $s.= '      <li><a href="' . $githubUrl . '" target="_blank">Github</a></li>'.N;
}
if ($this->user) {
    $s.= '      <li>'.N;
    $href = $this->url('projects/edit', array('slug' => $this->project->slug));
    $s.= '        <a href="' . $href . '">Edit</a>'.N;
    $s.= '      </li>'.N;
    $s.= '      <li>'.N;
    $href = $this->url('projects/delete', array('slug' => $this->project->slug)) . '?token=' . $this->csrfToken;
    $s.= '        <a href="' . $href . '" class="delete" data-prompt="Are you sure you want to delete this project?">Delete</a>'.N;
    $s.= '      </li>'.N;
}
$s.= '    </ul>'.N;
$s.= '  </div>'.N;
if ($this->project->intro) {
    $s.= '  <div class="intro">'.N;
    $s.= '    <p>' . $this->project->intro . '</p>'.N;
    $s.= '  </div>'.N;
}
$s.= '  <ul class="menu">'.N;
$s.= '    <li><a href="' . $this->url('projects/project', array('slug' => $this->project->slug)) . '">Description</a></li>'.N;
$s.= '    <li><a href="' . $this->url('projects/project', array('slug' => $this->project->slug)) . '">Documentation</a></li>'.N;
if (property_exists($this->project->github, 'username')) {
    $s.= '    <li><a href="' . $this->url('projects/history', array('slug' => $this->project->slug)) . '">History</a></li>'.N;
}
$s.= '  </ul>'.N;
$s.= '</aside>'.N;

print($s);