<?php

$s = '';

$s.= '<h2>Projects</h2>'.N;
foreach($this->projects as $project) {
    $s.= '<article>'.N;
    $s.= '  <h3><a href="' . $this->url('projects/project', array('slug' => $project->slug)) . '">' . $project->title . '</a></h3>'.N;
    $s.= '  <p>' . $project->intro . '</p>'.N;
    $s.= '</article>'.N;
}

$this->setSlot('pagetitle', 'Projects');
$this->setSlot('meta.description', 'An overview of projects I\'m currently working on or have worked on.');
$this->setSlot('meta.keywords', 'Pieter Hordijk, projects, github, opensource, oss, foss, development');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));