<?php

$s = '';

$s.= '<h2>Description</h2>'.N;
$s.= '<p>' . $this->markdown->parse($this->project->description) . '</p>'.N;

$this->setSlot('pagetitle', $this->project->title . ' - Projects');
$this->setSlot('meta.description', $this->project->intro);
$keywords = '';
if ($this->project->keywords) {
    $keywords = $this->project->keywords;
}
$this->setSlot('meta.keywords', $keywords);
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));