<?php

$s = '';

$s.= '<h2>Description</h2>'.N;
$s.= '<p>' . $this->markdown->parse($this->project->description) . '</p>'.N;

$this->setSlot('pagetitle', null);
$this->setSlot('meta.description', '');
$this->setSlot('meta.keywords', '');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));