<?php

$s = '';

$s.= '<h2>Description</h2>'.N;

$s.= '<div class="table-heading">Some title</div>'.N;
$s.= '<table>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Nicknames</th>'.N;
$s.= '    <td><input type="text" name="nickname" placeholder="Some placeholder" value="Testje"></td>'.N;
$s.= '  </tr>'.N;
$s.= '</table>'.N;

$this->setSlot('pagetitle', null);
$this->setSlot('meta.description', '');
$this->setSlot('meta.keywords', '');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));