<?php

$s = '';

$s.= '<h2>PieterHordijk.com</h2>'.N;

$s.= '<p>This is my personal website. This is the place where you can follow the projects I am currently working on and other stuff I find interesting. With the occasional rant against PHP. But hey, we all now that PHP sucks right? Than again once you know why PHP sucks you can use that knowledge and make it the best tool for the job.</p>'.N;

$this->setSlot('pagetitle', null);
$this->setSlot('meta.description', '');
$this->setSlot('meta.keywords', '');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));