<?php

$s = '';

$s.= '<aside>'.N;
$s.= '  <div class="info">'.N;
$s.= '    <div class="image">'.N;
$s.= '      <img src="/img/projects/mfw.png" alt="MicroFramework logo" title="MicroFramework logo">'.N;
$s.= '      <a href="#">Download</a>'.N;
$s.= '    </div>'.N;
$s.= '    <ul>'.N;
$s.= '      <li><strong>MicroFramework</strong></li>'.N;
$s.= '      <li><a href="https://github.com/PeeHaa/MicroFramework">GitHub</a></li>'.N;
$s.= '      <li>Follow</li>'.N;
$s.= '      <li>Fork</li>'.N;
$s.= '    </ul>'.N;
$s.= '  </div>'.N;
$s.= '  <div class="intro">'.N;
$s.= '    <p>MicroFramework is a lightweight framework written in PHP which utilizes the MVC pattern.</p>'.N;
$s.= '  </div>'.N;
$s.= '  <ul class="menu">'.N;
$s.= '    <li><a href="#">Description</a></li>'.N;
$s.= '    <li><a href="#">Documentation</a></li>'.N;
$s.= '    <li><a href="#">History</a></li>'.N;
$s.= '  </ul>'.N;
$s.= '</aside>'.N;

print($s);