<?php

$s = '';

$s.= '<div class="content">'.N;
$s.= '  <h1>' . 'PieterHordijk' . '</h1>'.N;
$s.= $this->render('base/usermenu.phtml');
$s.= '</div>'.N;

$s.= '<div class="mainmenu">'.N;
$s.= '  <ul>'.N;
$s.= '    <li class="active">'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Projects'.N;
$s.= '      </a>'.N;
$s.= '      <ul>'.N;
$s.= '        <li class="active first"><a href="#">MicroFramework</a></li>'.N;
$s.= '        <li class="last"><a href="#">cv-pls</a></li>'.N;
$s.= '      </ul>'.N;
$s.= '    </li>'.N;
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Tutorials'.N;
$s.= '      </a>'.N;
$s.= '      <ul>'.N;
$s.= '        <li class="first"><a href="#">MySQL in PHP using PDO - The right way ™</a></li>'.N;
$s.= '        <li class="last"><a href="#">cv-pls</a></li>'.N;
$s.= '      </ul>'.N;
$s.= '    </li>'.N;
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Lorem'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Ipsum'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Contact'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
$s.= '  </ul>'.N;
$s.= '</div>'.N;

$s.= '<div class="submenu">'.N;
$s.= '</div>'.N;

print($s);