<?php

$projectModel = $this->modelFactory->getModel('Project');
$projects = $projectModel->getProjects();

$tutorialModel = $this->modelFactory->getModel('Tutorial');
$tutorials = $tutorialModel->getTutorials();

$s = '';

$s.= '<div class="mainmenu">'.N;
$s.= '  <ul>'.N;
$active = '';
if (strpos($this->url(), $this->url('projects', array())) === 0) {
    $active = ' class="active"';
}
$s.= '    <li' . $active . '>'.N;
$s.= '      <a href="' . $this->url('projects', array()) . '">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Projects'.N;
$s.= '      </a>'.N;
$s.= '      <ul>'.N;
$classes = array('first');
foreach($projects as $project) {
    $active = '';
    if (strpos($this->url(), $this->url('projects/project', array('slug' => $project->slug))) === 0) {
        $classes[] = 'active';
    }
    $s.= '        <li class="' . implode(' ', $classes) . '"><a href="' . $this->url('projects/project', array('slug' => $project->slug)) . '">' . $project->title . '</a></li>'.N;

    $classes = array();
}
if ($this->user) {
    $s.= '        <li class="' . implode(' ', $classes) . '"><a href="' . $this->url('projects/create', array()) . '">Add new project</a></li>'.N;
}
$s.= '      </ul>'.N;
$s.= '    </li>'.N;
$active = '';
if (strpos($this->url(), $this->url('tutorials', array())) === 0) {
    $active = ' class="active"';
}
$s.= '    <li' . $active . '>'.N;
$s.= '      <a href="' . $this->url('tutorials', array()) . '">'.N;
$s.= '         <img src="/style/projects.png" alt="Tutorials" title="Tutorials">'.N;
$s.= '         Tutorials'.N;
$s.= '      </a>'.N;
$s.= '      <ul>'.N;
$classes = array('first');
foreach($tutorials as $tutorial) {
    $active = '';
    if (strpos($this->url(), $this->url('tutorials/tutorial', array('slug' => $tutorial->slug))) === 0) {
        $classes[] = 'active';
    }
    $s.= '        <li class="' . implode(' ', $classes) . '"><a href="' . $this->url('tutorials/tutorial', array('slug' => $tutorial->slug)) . '">' . $tutorial->title . '</a></li>'.N;

    $classes = array();
}
if ($this->user) {
    $s.= '        <li class="' . implode(' ', $classes) . '"><a href="' . $this->url('tutorials/create', array()) . '">Add new tutorial</a></li>'.N;
}
$s.= '      </ul>'.N;
$s.= '    </li>'.N;
$active = '';
if (strpos($this->url(), $this->url('music', array())) === 0) {
    $active = ' class="active"';
}
$s.= '    <li'. $active .'>'.N;
$s.= '      <a href="' . $this->url('music', array()) . '">'.N;
$s.= '         <img src="/style/projects.png" alt="Music" title="Music">'.N;
$s.= '         Music'.N;
$s.= '      </a>'.N;
$classes = array('first');
if ($this->user) {
    if (strpos($this->url(), $this->url('music/add', array())) === 0) {
        $classes[] = 'active';
    }
    $s.= '      <ul>'.N;
    $s.= '        <li class="' . implode(' ', $classes) . '"><a href="' . $this->url('music/add', array()) . '">Add new track</a></li>'.N;
    $s.= '      </ul>'.N;
}
$s.= '    </li>'.N;
/*
$s.= '    <li>'.N;
$s.= '      <a href="' . $this->url('benchmarks', array()) . '">'.N;
$s.= '         <img src="/style/projects.png" alt="Benchmarks" title="Benchmarks">'.N;
$s.= '         Benchmarks'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Sandbox'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
$active = '';
if (strpos($this->url(), $this->url('page/contact', array())) === 0) {
    $active = ' class="active"';
}
$s.= '    <li' . $active . '>'.N;
$s.= '      <a href="' . $this->url('page/contact', array()) . '">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Contact'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
*/
if ($this->user) {
    $active = '';
    if (strpos($this->url(), $this->url('user/register', array())) === 0) {
        $active = ' class="active"';
    }
    $s.= '    <li' . $active . '>'.N;
    $s.= '      <a href="' . $this->url('user/register', array()) . '">'.N;
    $s.= '         <img src="/style/projects.png" alt="User register" title="User register">'.N;
    $s.= '         User register'.N;
    $s.= '      </a>'.N;
    $s.= '    </li>'.N;
}
$s.= '  </ul>'.N;
$s.= '</div>'.N;

$s.= '<div class="submenu">'.N;
$s.= '</div>'.N;

print($s);