<?php

$projectModel = $this->modelFactory->getModel('Project');
$projects = $projectModel->getProjects();

$s = '';

$s.= '<div class="mainmenu">'.N;
$s.= '  <ul>'.N;
$s.= '    <li class="active">'.N;
$s.= '      <a href="' . $this->url('projects', array()) . '">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Projects'.N;
$s.= '      </a>'.N;
$s.= '      <ul>'.N;
$classes = array('first');
foreach($projects as $project) {
    $s.= '        <li class="' . implode(' ', $classes) . '"><a href="' . $this->url('projects/project', array('slug' => $project->slug)) . '">' . $project->title . '</a></li>'.N;

    $classes = array();
}
if ($this->user) {
    $s.= '        <li class="' . implode(' ', $classes) . '"><a href="' . $this->url('projects/create', array()) . '">Add new project</a></li>'.N;
}
$s.= '      </ul>'.N;
$s.= '    </li>'.N;
/*
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Tutorial" title="Tutorials">'.N;
$s.= '         Tutorials'.N;
$s.= '      </a>'.N;
$s.= '      <ul>'.N;
$s.= '        <li class="first"><a href="#">MySQL in PHP using PDO - The right way ™</a></li>'.N;
$s.= '        <li class="last"><a href="#">cv-pls</a></li>'.N;
$s.= '      </ul>'.N;
$s.= '    </li>'.N;
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Performance tests" title="Performance tests">'.N;
$s.= '         Performance tests'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
$s.= '    <li>'.N;
$s.= '      <a href="#">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Sandbox'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
*/
$s.= '    <li>'.N;
$s.= '      <a href="' . $this->url('page/contact', array()) . '">'.N;
$s.= '         <img src="/style/projects.png" alt="Projects" title="Projects">'.N;
$s.= '         Contact'.N;
$s.= '      </a>'.N;
$s.= '    </li>'.N;
if ($this->user) {
    $s.= '    <li>'.N;
    $s.= '      <a href="' . $this->url('user/register', array()) . '">'.N;
    $s.= '         <img src="/style/projects.png" alt="User register" title="User register">'.N;
    $s.= '         User register'.N;
    $s.= '      </a>'.N;
    $s.= '    </li>'.N;
}
$s.= '  </ul>'.N;
$s.= '</div>'.N;

$s.= '<div class="submenu">'.N;
$s.= '</div>'.N;

print($s);