<?php

$menu = $this->defaultSlot('menu', null);
if (!$menu) return;

$s = '';

foreach($menu as $item) {

    if (!$this->has_access($item['accesslevel'], $item)) continue;

    if ($this->url() == $item['url']) {
        if (isset($item['attributes']['class'])) {
            $item['attributes']['class'].= ' active';
        } else {
            $item['attributes']['class'] = 'active';
        }
    }

    // parse attributes
    $attributearray = array();
    $href_attributes = array();
    if ($item['attributes']) {
        foreach($item['attributes'] as $attr=>$val) {
            if ($attr == 'target') {
                $href_attributes[] = $attr.'="'.$val.'"';
                continue;
            }
            $attributearray[] = $attr.'="'.$val.'"';
        }
    }

    $attributes = null;
    if ($attributearray) {
        $attributes = ' '.implode(' ', $attributearray);
    }

    $attributes = null;
    if ($attributearray) {
        $attributes = ' '.implode(' ', $attributearray);
    }

    $hrefattrs = null;
    if ($href_attributes) {
        $hrefattrs = ' '.implode(' ', $href_attributes);
    }

    $s.= '    <li'.$attributes.'><a href="'.$item['url'].'"'.$hrefattrs.'>'.$item['title'].'</a>'.N;
    if (array_key_exists('children', $item) && $item['children']) {
        $s.= '      <ul class="submenu">'.N;
        $this->setSlot('menu', $item['children']);
        $s.= $this->render('base/menu-items.phtml');
        $s.= '      </ul>'.N;
    }
    $s.= '    </li>'.N;
}

print($s);