<?php

//if ($this->user) {
if (1 == 2) {
    $authMenu = array('img' => '/style/user.png',
                      'alt' => 'Log out',
                      'title' => 'Log out' . $this->user->username,
                      );
} else {
    $authMenu = array('img' => '/style/user.png',
                      'alt' => 'Log in',
                      'title' => 'Log in',
                      );
}

$s = '';


$s.= '<ul class="usermenu">'.N;
$s.= '  <li>'.N;
$s.= '    <img src="' . $authMenu['img'] . '" alt="' . $authMenu['alt'] . '" title="' . $authMenu['title'] . '">'.N;
$s.= '  </li>'.N;
$s.= '  <li class="loginform" style="display: inline;">'.N;
$loginForm = new User_Login_Form();
$this->setSlot('form', $loginForm);
$s.= '    <form action="' . $this->url('user/login', array()) . '" method="post">'.N;
$this->setSlot('form.field', 'csrf-token');
$s.= $this->render('form/render_formfield.phtml').N;
$this->setSlot('form.field', 'username');
$s.= $this->render('form/render_formfield.phtml').N;
$this->setSlot('form.field', 'password');
$s.= $this->render('form/render_formfield.phtml').N;
$this->setSlot('form.field', 'submit');
$s.= $this->render('form/render_formfield.phtml').N;
$s.= '    </form>'.N;
$s.= '  </li>'.N;
$s.= '  <li class="last login">'.N;
$s.= '    <a href="' . $this->url() . '">' . $authMenu['title'] . '</a>'.N;
$s.= '  </li>'.N;
$s.= '</ul>'.N;

print($s);