<?php

$this->setSlot('form', $this->form);

$s = '';

$s.= '<h2>Create a new user</h2>'.N;

$s.= '<div class="table-heading">Some title</div>'.N;
$s.= '<form action="" method="post">'.N;
$this->setSlot('form.field', 'csrf-token');
$s.= $this->render('form/render_formfield.phtml');
$s.= '<table>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Username *</th>'.N;
$this->setSlot('form.field', 'username');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Password *</th>'.N;
$this->setSlot('form.field', 'password');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>Emailaddress</th>'.N;
$this->setSlot('form.field', 'email');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '  <tr>'.N;
$s.= '    <th>&nbsp;</th>'.N;
$this->setSlot('form.field', 'submit');
$s.= '    <td>' . $this->render('form/render_formfield.phtml') . '</td>'.N;
$s.= '  </tr>'.N;
$s.= '</table>'.N;
$s.= '</form>'.N;

$this->setSlot('pagetitle', null);
$this->setSlot('meta.description', '');
$this->setSlot('meta.keywords', '');
$this->setSlot('meta.author', 'Pieter Hordijk');
$this->setSlot('meta.revisit-after', '1 month');

$this->setSlot('content', $s);

print($this->render('base/page.phtml'));